#! /bin/bash
ROOTPATH="$(pwd)"
CLUSTER_DIR="$(pwd)/cluster"
QUSTION_PATH="$(pwd)/config/question"
LOGDIR="${ROOTPATH}/logs"
TRANSPORTERRORLOGPATH="${LOGDIR}/transport_error.log"
TRANSPORTLOGPATH="${LOGDIR}/transport.log"
YMLFILE='elasticsearch.yml'
JVMDIR='jvm.options.d'
JVMFILE='jvm.options'
SEVERFILE='server'
questionPath='/home/ec2-user/escue/config/question'

# elasticsearch.yml
cluster_name="cluster.name"
node_name="node.name"
http_host="network.host"
http_port="http.port"
node_roles="node.roles"
data_path="path.data"
logs_path="path.logs"
seed_hosts="discovery.seed_hosts"
initial_master_nodes="cluster.initial_master_nodes"

# server
config_path="config.path"
install_path="install.path"
server_user_name="server.username"
server_host="server.host"

# jvm
jvm_heap="jvm.heap"



